server:
  port: 8088

mybatis:
  typeAliasesPackage: com.nuoya.springdayone.entity
  mapperLocations: classpath:mapper/*.xml
# 打印sql
logging:
  level:
    com.nuoya.springdayone.dao :  debug

spring:
  mvc:
    view:
      prefix: /view/
      suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=UTF-8&serverTimezone=UTC&&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  type: com.alibaba.druid.pool.DruidDataSource
  　　　　initialSize: 1
  　　　　minIdle: 3
  　　　　maxActive: 20
  　　　　maxWait: 60000
  　　　　timeBetweenEvictionRunsMillis: 60000
  　　　　minEvictableIdleTimeMillis: 30000
  　　　　validationQuery: select 'x'
  　　　　testWhileIdle: true
  　　　　testOnBorrow: false
  　　　　testOnReturn: false
  　　　　poolPreparedStatements: true
  　　　　maxPoolPreparedStatementPerConnectionSize: 20
  　　　　filters: stat,wall,slf4j
  　　　　connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  　　　　useGlobalDataSourceStat: true


